---
configure_explorer: true
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remove_desktop_icons: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: true
choco_installed_packages:
  - zoom
  # TODO: Add the other packages

install_winget_packages: true
winget_packages:
  # - name: "Auto Dark Mode"
  #   source: winget

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

configure_storage_sense: true
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 30
  delete_downloads_files: true
  downloads_age: 30
