---
source_key: ".ssh/id_ed25519"
dest_key: "{{ ansible_env.USERPROFILE }}\\.ssh\\id_ed25519"
personal: "{{ ansible_env.USERPROFILE }}"

configure_explorer: true
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remove_desktop_icons: true

install_windows_updates: false
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

install_chocolatey_packages: false
choco_installed_packages:

# core
  - powershell-core
  - dropbox
  - fd
  - Firefox
  - fzf
  - git
  - zoxide
  - vscode
  - ripgrep
  - discord
  - keepass
  - make
  - neovim
  - thunderbird
  - spotify
  - powertoys
  - googledrive
  - gsudo

# work
  - slack
  - zoom
  - nodejs
  - dotnet-sdk
  - jetbrains-rider

# other
  - 7zip
  - adobereader
  - chromium
  - coretemp
  - gimp
  - GoogleChrome
  - libreoffice
  - obsidian
  - postman
  - python312
  - rufus
  - todoist-desktop
  - unzip

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams
  - Microsoft.Instagram

configure_storage_sense: true
storage_sense:
  enabled: true
  run_frequency: 1
  delete_unused_files: true
  delete_recycle_bin_files: true
  recycle_bin_age: 30
  delete_downloads_files: true
  downloads_age: 30

dotfiles:
  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\git\\.gitconfig"
    dest: "{{ ansible_env.USERPROFILE }}\\.gitconfig"

  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\git\\.gitmessage"
    dest: "{{ ansible_env.USERPROFILE }}\\.gitmessage"

  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\git\\.gitconfig-work"
    dest: "{{ ansible_env.USERPROFILE }}\\.gitconfig-work"

  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\windows-terminal/LocalAppData/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
    dest: "{{ ansible_env.USERPROFILE }}\\AppData\\Local\\Microsoft\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"

  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\ideavim\\.ideavimrc"
    dest: "{{ ansible_env.USERPROFILE }}\\.ideavimrc"

  - src: "{{ ansible_env.USERPROFILE }}\\personal\\code\\dotfiles\\powerhsell\\Microsoft.PowerShell_profile.ps1"
    dest: "{{ ansible_env.USERPROFILE }}\\Documents\\PowerShell"