---
- name: Windows Playbook
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook user configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

    - name: Clone win_git fork
      git:
        repo: 'https://github.com/joaosilvanogueira/ansible-win_git.git'
        dest: '{{ playbook_dir }}/win_git'
        version: master
      delegate_to: localhost
      tags: ["always"]

    - name: Copy win_git scripts to DEFAULT_MODULE_PATH
      local_action:
        module: copy
        src: "{{ item }}"
        dest: "{{ lookup('env', 'HOME') }}/.ansible/plugins/module_utils/"
      with_fileglob:
        - "{{ playbook_dir }}/win_git/*.py"
        - "{{ playbook_dir }}/win_git/*.ps1"
      tags: ["always"]

  tasks:
    - name: Include debloat configuration.
      ansible.builtin.import_tasks:
        file: tasks/debloat.yml
      when: remove_bloatware
      tags: ["debloat"]

    - name: Include ssh configuration.
      ansible.builtin.import_tasks:
        file: tasks/ssh.yml
      tags: ["ssh"]

    - name: Include windows updates configuration.
      ansible.builtin.import_tasks:
        file: tasks/updates.yml
      when: install_windows_updates
      tags: ["updates"]


    - name: Include chocolatey configuration.
      ansible.builtin.import_tasks:
        file: tasks/chocolatey.yml
      when: install_chocolatey_packages
      tags: ["choco"]

    - name: Include fonts configuration.
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include explorer configuration.
      ansible.builtin.import_tasks:
        file: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]

    - name: Include taskbar configuration.
      ansible.builtin.import_tasks:
        file: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]

    - name: Include start menu configuration.
      ansible.builtin.import_tasks:
        file: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu"]

    - name: Include mouse configuration.
      ansible.builtin.import_tasks:
        file: tasks/mouse.yml
      when: disable_mouse_acceleration
      tags: ["mouse"]

    - name: Include power plan configuration.
      ansible.builtin.import_tasks:
        file: tasks/power_plan.yml
      when: change_power_plan
      tags: ["power"]

    - name: Include desktop configuration.
      ansible.builtin.import_tasks:
        file: tasks/desktop.yml
      when: remove_desktop_icons
      tags: ["desktop"]

    - name: Include storage sense configuration.
      ansible.builtin.import_tasks:
        file: tasks/storage.yml
      when: configure_storage_sense
      tags: ["storage_sense"]

    - name: Import dotfiles with symlink
      ansible.builtin.import_tasks:
        file: tasks/dotfiles.yml
      tags: ["dotfiles"]

    - name: git clones
      ansible.builtin.import_tasks:
        file: tasks/git.yml
      tags: ["git"]
