- name: Ensure destination directories exist
  win_file:
    path: "{{ item.dest | win_dirname }}"
    state: directory
  loop: "{{ dotfiles }}"

- name: Create symlink for dotfile
  win_shell: |
    $source = "{{ item.src }}"
    $target = "{{ item.dest }}"
    if (Test-Path $target) {
      Remove-Item $target -Force
    }
    New-Item -ItemType SymbolicLink -Path $target -Target $source -Force
  loop: "{{ dotfiles }}"

- name: Display symlink creation result
  debug:
    msg: "Symlink created: {{ item.dest }} -> {{ item.src }}"
  loop: "{{ dotfiles }}"

  # TODO: Add powershell!
  # TODO: Check nuget.config
